name: Publish to Rubygems

on:
  push:
    branches:
      - refs/tags/v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Rubygems
      uses: cadwallion/publish-rubygems-action@v1.0.0
